config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home"
  
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users, except: [:new, :create]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]

    resources :follows do
      member do
        get :following, :followers
      end
    end

    resources :relationships, only: [:create, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "errors.the_form_contains" %> <%= pluralize object.errors.count, t("errors.error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="text-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <div class="pagy mt-3">
    <%= paginate @feed_items, theme: "twitter-bootstrap-4",
      params: { controller: :static_pages, action: :home } %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.text_area :content, placeholder: t("micropost.new_micropost"), class: "form-control", rows: Settings.layout.rows %>
  </div>
  <span class="image">
    <%= f.file_field :image, accept: Settings.validation.accept_image %>
  </span>
  <%= f.submit t("micropost.post"), class: "btn btn-primary btn-block mt-2" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="row">
  <div class="col-5">
    <div class="d-flex flex-column bd-highlight mb-3">
      <div class="p-2 bd-highlight">
        <%= link_to following_follow_path(@user) do %>
          <strong id="following" class="stat">
            <%= @user.following.count %>
          </strong>
          <%= t "follow.following" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-6">
    <div class="d-flex flex-column bd-highlight mb-3">
      <div class="p-2 bd-highlight">
        <%= link_to followers_follow_path(@user) do %>
          <strong id="following" class="stat">
            <%= @user.followers.count %>
          </strong>
          <%= t "follow.followers" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_info.html.erb
<p>
  <%= link_to gravatar_for(current_user), current_user %>
  <%= current_user.name %>
</p>
<span><%= link_to t("micropost.view_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t("micropost.micropost") %></span>