config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home"
  
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users, except: [:new, :create]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]

    resources :follows do
      member do
        get :following, :followers
      end
    end

    resources :relationships, only: [:create, :destroy]
  end
end

app/views/layouts/_header.html.erb
<nav id="navbar-example2" class="navbar navbar-light bg-dark">
  <%= link_to t("static_pages.sample_app"), root_url, class: "text-light" %>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("static_pages.home"), root_url, class: "nav-link text-light" %>
    </li>
    <li class="nav-item">
      <%= link_to t("static_pages.help"), help_path, class: "nav-link text-light" %>
    </li>
    <% if logged_in? %>
      <div class="dropdown">
        <%= link_to "#", class: "btn text-light dropdown-toggle", "data-toggle": "dropdown" do %>
          <%= t "static_pages.account" %>
        <% end %>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li>
            <%= link_to t("static_pages.all_users"), users_path, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to t("static_pages.profile"), current_user, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to t("static_pages.setting"), edit_user_path(current_user), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to t("auth.logout"), logout_path, method: :delete, class: "dropdown-item" %>
          </li>
        </div>
      </div>
    <% else %>
      <li class="nav-item">
        <%= link_to t("auth.login"), login_path, class: "nav-link text-light" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <script>
      var language = "<%= I18n.locale %>";
      I18n.translations = <%== I18n::JS.filtered_translations.to_json %>;
    </script>
  </head>

  <body>
    <div class="ml-3">
      <%= link_to t("language.en"), locale: "en" %>
      <%= link_to t("language.vi"), locale: "vi" %>
    </div>
    <%= render "layouts/header" %>
    <div class="container mt-3">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>

    <%= javascript_pack_tag "custom" %>
  </body>
</html>